name: pipeline-main

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - dev-0
jobs:
    # main: 
    #     uses: ddruk-landing-zone-0/sample-python-wsgi-prod-app/.github/workflows/python-gcp-main.yml@main
    #     secrets: inherit
    #     with:
    #         GCP_PROJECT_ID: hackathon0-project
    #         CLOUD_RUN_SERVICE: sample-python-prod-server
    #         CLOUD_RUN_REGION: us-central1
    #         GAR_LOCATION: us-central1-docker.pkg.dev/hackathon0-project/python-prod-server
    #         GAR_LOCATION_PREFIX: us-central1-docker.pkg.dev
    #         IMAGE_NAME: sample-python-prod-server-image
    #         SERVICE_ACCOUNT: hackathon0-sa@hackathon0-project.iam.gserviceaccount.com
    #         DOCKER_FILE: Dockerfile.app
    #         CLOUD_RUN_RAM: 512Mi

    python-aws:
        uses: agricapt-hack/backend/.github/workflows/python-awsec2-main.yml@main
        secrets: inherit
        with:
            DOCKER_FILE: "./Dockerfile.app"
            IMAGE_NAME: capital-one-server-image
            CONTAINER_NAME: capital-one-1
            APP_DIR: "/home/ubuntu/app"
            APP_PORT: "8080"
            